### ISSUE TITLE
textures isssues

### ISSUE THREAD

**Issue by dawsontech30000** [ElectrifiedDed/ElectrifiedDed-ThaumicEnergistics-main#1]
![image](https://github.com/ElectrifiedDed/ElectrifiedDed-ThaumicEnergistics-main/assets/46389381/17e1566b-b8ac-4c32-a87c-2c1d5650626f)
![image](https://github.com/ElectrifiedDed/ElectrifiedDed-ThaumicEnergistics-main/assets/46389381/69e809d1-9c3d-4a8d-b476-c71e19c7b36f)
![image](https://github.com/ElectrifiedDed/ElectrifiedDed-ThaumicEnergistics-main/assets/46389381/2c2f886b-bf69-4375-9e24-68fee3325449)
![image](https://github.com/ElectrifiedDed/ElectrifiedDed-ThaumicEnergistics-main/assets/46389381/c9a514c9-c26a-42ab-9e0b-648da0a4efc7)
![image](https://github.com/ElectrifiedDed/ElectrifiedDed-ThaumicEnergistics-main/assets/46389381/9012adc6-d51a-4249-98d0-4c9e81fa8398)
![image](https://github.com/ElectrifiedDed/ElectrifiedDed-ThaumicEnergistics-main/assets/46389381/14534302-9354-46d1-95db-3ccaaa80a7de)
![image](https://github.com/ElectrifiedDed/ElectrifiedDed-ThaumicEnergistics-main/assets/46389381/fc3f765d-2535-4dac-872c-3941d5d6d9c9)

**Comment by ElectrifiedDed** [comment]
Yes, this is a temporary measure. at the moment, I can't add textures to them since there are no sources in this style.

**Comment by dawsontech30000** [comment]
will it be fixed in future ? as you say temp fixed

**Comment by ElectrifiedDed** [comment]
yes it will be fixed.
