### ISSUE TITLE
The GUI failed to close after the arcane terminal was destroyed causing the item to copy

### ISSUE THREAD

**Issue by mustardwheat** [ElectrifiedDed/ElectrifiedDed-ThaumicEnergistics-main#2]
https://github.com/ElectrifiedDed/ElectrifiedDed-ThaumicEnergistics-main/assets/88693726/097857b4-6c41-489b-8659-ceedd0cd95a7

version
thaumicenergistics-extended_life-2.3.1(2.2.7)

**Comment by ElectrifiedDed** [comment]
I will try to fix it.

**Comment by ElectrifiedDed** [comment]
fixed
