### ISSUE TITLE
crash when i used  this mod in server

### ISSUE THREAD

**Issue by PathdarX** [ElectrifiedDed/ElectrifiedDed-ThaumicEnergistics-main#5]
[crash-2024-08-03_16.28.42-server.txt](https://github.com/user-attachments/files/16478727/crash-2024-08-03_16.28.42-server.txt)

**Comment by ElectrifiedDed** [comment]
[thaumicenergistics-extended_life-2.4.5(2.2.7).zip](https://github.com/user-attachments/files/16478792/thaumicenergistics-extended_life-2.4.5.2.2.7.zip)


could you try it with this version

**Comment by PathdarX** [comment]
ok, thank you, I will use this version later
